apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yml
  - service.yml

images:
  - name: price-api-image-placeholder
    newName: price-api
    newTag: latest
