spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: false
  sql:
    init:
      mode: always
      separator: "^^"
  h2:
    console:
      enabled: false
server:
  port: 8080
